def temp1():
	f = open("1template.txt","w+")
	f.write("==========================\n")
	f.write("Personal Information\n")
	f.write("\n")
	f.write("Full name: \n")
	f.write("Emails:  \n")
	f.write("Passwords:  \n")
	f.write("==========================\n")
	f.write("Social Media\n")
	f.write("\n")
	f.write("Twitter: \n")
	f.write("Discord:  \n")
	f.write("Facebook:  \n")
	f.write("==========================\n")
	f.write("Location\n")
	f.write("\n")
	f.write("Address: \n")
	print('Basic Template Created!')
	f.close()

def temp2():
	f = open("2template.txt","w+")
	f.write("==========================\n")
	f.write("Personal Information\n")
	f.write("\n")
	f.write("Full name: \n")
	f.write("Emails:  \n")
	f.write("Passwords:  \n")
	f.write("Phone: \n")
	f.write("==========================\n")
	f.write("Social Media Platforms\n")
	f.write("\n")
	f.write("Twitter: \n")
	f.write("Discord:  \n")
	f.write("Facebook:  \n")
	f.write("Snapchat: \n")
	f.write("==========================\n")
	f.write("Location\n")
	f.write("\n")
	f.write("Address: \n")
	f.write("==========================\n")
	f.write("IP Information\n")
	f.write("\n")
	f.write("IP: \n")
	f.write("ISP: \n")
	print('Semi Basic Template Created!')
	f.close()

def temp3():
	f = open("3template.txt","w+")
	f.write("==========================\n")
	f.write("Personal Information\n")
	f.write("\n")
	f.write("Full name: \n")
	f.write("Email(s):  \n")
	f.write("- \n")
	f.write("- \n")
	f.write("- \n")
	f.write("- \n")
	f.write("\n")
	f.write("Password(s): \n")
	f.write("- \n")
	f.write("- \n")
	f.write("- \n")
	f.write("- \n")
	f.write("\n")
	f.write("Phone: \n")
	f.write("Card Number: \n")
	f.write("==========================\n")
	f.write("Social Media Platforms\n")
	f.write("\n")
	f.write("Twitter: \n")
	f.write("Discord:  \n")
	f.write("Facebook:  \n")
	f.write("Snapchat: \n")
	f.write("Reddit: \n")
	f.write("YouTube: \n")
	f.write("GooglePlus: \n")
	f.write("NameMC: \n")
	f.write("Instagram: \n")
	f.write("==========================\n")
	f.write("Location Information\n")
	f.write("\n")
	f.write("Street: \n")
	f.write("Town / City: \n")
	f.write("County / State: \n")
	f.write("Country: \n")
	f.write("Postal Code: \n")
	f.write("==========================\n")
	f.write("Iternet Protocol Information\n")
	f.write("\n")
	f.write("Current IP: \n")
	f.write("\n")
	f.write("Past IP(s): \n")
	f.write("- \n")
	f.write("- \n")
	f.write("- \n")
	f.write("\n")
	f.write("ISP: \n")
	f.write("ASN Number: \n")
	f.write("==========================\n")
	f.write("Family Information Information\n")
	f.write("\n")
	f.write("Full name: \n")
	f.write("Facebook: \n")
	f.write("Image: \n")
	f.write("\n")
	f.write("Full name: \n")
	f.write("Facebook: \n")
	f.write("Image: \n")
	f.write("\n")
	f.write("Full name: \n")
	f.write("Facebook: \n")
	f.write("Image: \n")
	f.write("\n")
	f.write("Full name: \n")
	f.write("Facebook: \n")
	f.write("Image: \n")
	f.write("==========================\n")
	f.write("Credits\n")
	f.write("\n")
	f.write("SE By: \n")
	f.write("How To Detrace...: \n")
	print('Large Template Created!')
	f.close()